### ISSUE TITLE
[Backend] Server Deploy

### ISSUE THREAD

**Issue by deploy-soon** [swsnu/swpp2019-team6#52]
백엔드 통신을 위한 서버를 제 azure 서버에 구축하고 있습니다.
domain은 굳이 안 받고 ip 그대로 통신하고자 합니다.

### checklist

- [ ] build virtual environment for python django
- [ ] install requirements
- [ ] MySQL setting, grant users
- [ ] Separate django settings.py code into deployment and local test.
- [ ] backend port setting
- [ ] local CORS test

**Comment by deploy-soon** [comment]
**[INFO]**

- 현재 `master` branch의 Frontend를 `http://52.141.3.238:80`에서 확인할 수 있습니다.

**[TODO]**
-  backend deploy
- url 등록
-  ssl 등록
- Dockerfile


cc. @dreamsh19 @jangdonghae @RXWE

**Comment by deploy-soon** [comment]
For Linux (ubuntu 18.04) install MySQL

```
$ virtualenv --python=python3 backend
$ source backend/bin/activate
$ cd swpp2019-team6/backend
$ pip install -r requirements.txt

$ sudo apt get libmysqlclient-dev
$ sudo apt get python3-dev
$ pip install mysqlclient
```

**Comment by deploy-soon** [comment]
For Linux (ubuntu 18.04) run backend 

```
(backend) $ python manage.py migrate --settings=triplannet.settings.deploy
(backend) $ python manage.py runserver --settings=triplannet.settings.deploy
```

**Comment by jangdonghae** [comment]
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
와 같은 에러가 뜨시는 경우

$ sudo apt-get install libssl-dev
로 해결하시면 됩니다
